export const SidebarMenuData = [
  {
    id: "{e06b5724-2866-4a41-88c2-6288ebc7883b}",
    pageName: "What we do",
    displayName: "What We do",
    altDisplayName: "Te reo translation",
    path: "/what-we-do",
    isExternalLink: false,
    children: [
      {
        id: "{b87d44fe-4948-4c42-95d5-9afbf9dc76a2}",
        pageName: "Monetary Policy",
        displayName: "Monetary policy",
        altDisplayName: "",
        path: "/what-we-do/monetary-policy",
        isExternalLink: false,
        children: [
          {
            id: "{a66e2285-4464-46e2-a5ef-0b74206d9e32}",
            pageName: "Monetary policy statement latest",
            displayName: "Monetary policy statement (latest)",
            altDisplayName: "",
            path: "",
            isExternalLink: false,
            children: [],
          },
          {
            id: "{155585e7-dcb5-4d91-981f-b65b6238eec0}",
            pageName: "About monetary policy",
            displayName: "About monetary policy",
            altDisplayName: "",
            path: "",
            isExternalLink: false,
            children: [
              {
                id: "{328a4b98-0de8-41b2-a9b1-fc312ffffe35}",
                pageName: "Monetary policy Framework",
                displayName: "Monetary policy Framework",
                altDisplayName: "",
                path: "",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{ce295b7c-3377-4ff2-93c8-4e3b8a0089d2}",
                pageName: "Monetary policy Handbook",
                displayName: "Monetary policy Handbook",
                altDisplayName: "",
                path: "",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{93155049-49fd-4447-b081-795b59c2c0fd}",
                pageName: "Official cash rate",
                displayName: "Official cash rate",
                altDisplayName: "",
                path: "",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{de2c9323-b96d-46d9-a6f9-d1ee019cdb6b}",
                pageName: "History of Policy Target Agreements",
                displayName: "History of Policy Target Agreements",
                altDisplayName: "",
                path: "",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{c0685c5f-5952-49dd-ade2-a18efecc217d}",
                pageName: "Monetary policy decisions",
                displayName: "Monetary policy decisions",
                altDisplayName: "",
                path: "",
                isExternalLink: false,
                children: [],
              },
            ],
          },
          {
            id: "{75a0a128-4925-43c7-ac53-0ba530ef245f}",
            pageName: "Tools to support the economy",
            displayName: "Tools to support the economy",
            altDisplayName: "",
            path: "/what-we-do/monetary-policy/tools-to-support-the-economy",
            isExternalLink: false,
            children: [
              {
                id: "{13913127-add7-4712-81fa-2f64eaf2243e}",
                pageName: "Negative Official Cash Rate",
                displayName: "Negative official cash rate",
                altDisplayName: "",
                path: "/what-we-do/monetary-policy/tools-to-support-the-economy/negative-official-cash-rate",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{5c1931ca-8751-4505-831c-dc3845b08bc6}",
                pageName: "Funding for lending programme",
                displayName: "Funding for lending programme",
                altDisplayName: "",
                path: "",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{222ecb34-a927-499b-a2e4-24fa63de1a6d}",
                pageName: "Large-scale asset purchases",
                displayName: "Large-scale asset purchases",
                altDisplayName: "",
                path: "",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{b700b791-61f5-4501-a149-0030da8996af}",
                pageName: "Principles governing our monetary tools",
                displayName: "Principles governing our monetary tools",
                altDisplayName: "",
                path: "",
                isExternalLink: false,
                children: [],
              },
            ],
          },
          {
            id: "{3a77dde2-1e0e-4b6d-b6f8-550a28d8fc2d}",
            pageName: "Inflation",
            displayName: "Inflation",
            altDisplayName: "",
            path: "",
            isExternalLink: false,
            children: [
              {
                id: "{ee44cc41-827f-4a79-a2de-89a6c1079d78}",
                pageName: "Inflation calculator",
                displayName: "Inflation calculator",
                altDisplayName: "",
                path: "",
                isExternalLink: false,
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "{48911e7d-d84c-4f0c-8d7b-370378de61a3}",
        pageName: "Financial Stability",
        displayName: "Financial stability",
        altDisplayName: "",
        path: "/what-we-do/financial-stability",
        isExternalLink: false,
        children: [
          {
            id: "{4ca99934-afbe-4ec8-879f-640d2159c635}",
            pageName: "New Zealand Financial System",
            displayName: "New Zealand Financial System",
            altDisplayName: "",
            path: "/what-we-do/financial-stability/new-zealand-financial-system",
            isExternalLink: false,
            children: [
              {
                id: "{ebdb2478-4468-4c52-813a-204639690654}",
                pageName: "Financial market infrastructures",
                displayName: "Financial market infrastructures",
                altDisplayName: "",
                path: "/what-we-do/financial-stability/new-zealand-financial-system/financial-market-infrastructures",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{6ebcfd49-f6a8-4932-b851-ca37da5cc377}",
                pageName: "Insurance sector",
                displayName: "Insurance sector",
                altDisplayName: "",
                path: "/what-we-do/financial-stability/new-zealand-financial-system/insurance-sector",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{8aeeabc9-346f-4e1a-b1bc-50460f351cf5}",
                pageName: "Non-bank lending institutions",
                displayName: "Non-bank lending institutions",
                altDisplayName: "",
                path: "/what-we-do/financial-stability/new-zealand-financial-system/non-bank-lending-institutions",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{74a17b70-45eb-42be-8aaf-cdb02ef87c1d}",
                pageName: "The banking sector",
                displayName: "The banking sector",
                altDisplayName: "",
                path: "/what-we-do/financial-stability/new-zealand-financial-system/the-banking-sector",
                isExternalLink: false,
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "{dea958e5-baa3-4351-a93d-b7ba24d1c391}",
        pageName: "Have your say",
        displayName: "Have your say",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
      {
        id: "{228aff45-1e1c-4895-9a28-23b1090f5ab0}",
        pageName: "Payments and Settlement Systems",
        displayName: "Payments \u0026 Settlement Systems",
        altDisplayName: "",
        path: "/what-we-do/payments-and-settlement-systems",
        isExternalLink: false,
        children: [],
      },
      {
        id: "{d28619bf-c51f-47a8-885a-b9acd590b975}",
        pageName: "Markets",
        displayName: "Markets",
        altDisplayName: "",
        path: "",
        isExternalLink: true,
        children: [],
      },
      {
        id: "{6d0f9fc2-61e6-4160-828c-eb3ff7d10a2d}",
        pageName: "Regulation and supervision",
        displayName: "Regulation \u0026 supervision",
        altDisplayName: "",
        path: "/what-we-do/regulation-and-supervision",
        isExternalLink: false,
        children: [
          {
            id: "{36d61ed8-7648-4b2f-8ecd-3125186400aa}",
            pageName: "Banking oversight",
            displayName: "Banking oversight",
            altDisplayName: "",
            path: "/what-we-do/regulation-and-supervision/banking-oversight",
            isExternalLink: false,
            children: [
              {
                id: "{7c54bc91-b7f5-4ce6-8823-ca1d0a9e3cfc}",
                pageName: "How we regulate",
                displayName: "How we regulate",
                altDisplayName: "",
                path: "/what-we-do/regulation-and-supervision/banking-oversight/how-we-regulate",
                isExternalLink: false,
                children: [
                  {
                    id: "{6a5b1ffc-841d-4cbf-ac39-2a61c290ff73}",
                    pageName: "Covered Bonds",
                    displayName: "Covered Bonds",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/banking-oversight/how-we-regulate/covered-bonds",
                    isExternalLink: false,
                    children: [
                      {
                        id: "{030ca171-caf1-480e-a32d-c891c375cc02}",
                        pageName:
                          "Register of registered covered bonds programmes",
                        displayName:
                          "Register of registered covered bonds programmes",
                        altDisplayName: "",
                        path: "/what-we-do/regulation-and-supervision/banking-oversight/how-we-regulate/covered-bonds/register-of-registered-covered-bonds-programmes",
                        isExternalLink: false,
                        children: [],
                      },
                    ],
                  },
                  {
                    id: "{325174c8-4872-4005-8d28-17aa8fdaa405}",
                    pageName: "Thematic review of Banks",
                    displayName: "Thematic review of Banks",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/banking-oversight/how-we-regulate/thematic-review-of-banks",
                    isExternalLink: false,
                    children: [],
                  },
                ],
              },
              {
                id: "{c96d08fd-7d02-4419-b409-dbb3f26cb0f5}",
                pageName: "Standards and Requirements",
                displayName: "Standards and Requirements",
                altDisplayName: "",
                path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements",
                isExternalLink: false,
                children: [
                  {
                    id: "{075d71cc-12ca-4ada-bbd0-ab10736d5697}",
                    pageName: "Macroprudential policy",
                    displayName: "Macroprudential policy",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/macroprudential-policy",
                    isExternalLink: false,
                    children: [
                      {
                        id: "{2eb873d9-88c6-43af-a670-bb7ae2a81739}",
                        pageName: "LVR restrictions",
                        displayName: "LVR restrictions",
                        altDisplayName: "",
                        path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/macroprudential-policy/lvr-restrictions",
                        isExternalLink: false,
                        children: [],
                      },
                      {
                        id: "{6e6d145c-1ee7-4792-80b6-f57c90b260a3}",
                        pageName: "Macroprudential tools",
                        displayName: "Macroprudential tools",
                        altDisplayName: "",
                        path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/macroprudential-policy/macroprudential-tools",
                        isExternalLink: false,
                        children: [],
                      },
                      {
                        id: "{ebb83d35-b59a-45c6-9a08-29c79f085e4e}",
                        pageName: "Timeline for LVR restrictions",
                        displayName: "Timeline for LVR restrictions",
                        altDisplayName: "",
                        path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/macroprudential-policy/timeline-for-lvr-restrictions",
                        isExternalLink: false,
                        children: [],
                      },
                    ],
                  },
                  {
                    id: "{bac42674-701f-409a-97eb-623661ceedd4}",
                    pageName: "Capital adequacy framework",
                    displayName: "Capital adequacy framework",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/capital-adequacy-framework",
                    isExternalLink: false,
                    children: [
                      {
                        id: "{f1927401-dd57-438d-99e8-7a2ef69bb98f}",
                        pageName: "Capital requirements",
                        displayName: "Capital requirements",
                        altDisplayName: "",
                        path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/capital-adequacy-framework/capital-requirements",
                        isExternalLink: false,
                        children: [],
                      },
                      {
                        id: "{b269f925-2501-4d52-bd56-12837edfb486}",
                        pageName: "Capital review",
                        displayName: "Capital review",
                        altDisplayName: "",
                        path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/capital-adequacy-framework/capital-review",
                        isExternalLink: false,
                        children: [],
                      },
                      {
                        id: "{cf132387-fe54-47fe-a59a-bc9d539f746d}",
                        pageName:
                          "How we applied the Basel framework to capital requirements",
                        displayName:
                          "How we applied the Basel framework to capital requirements",
                        altDisplayName: "",
                        path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/capital-adequacy-framework/how-we-applied-the-basel-framework-to-capital-requirements",
                        isExternalLink: false,
                        children: [],
                      },
                      {
                        id: "{2b44a2ce-f51a-41f8-98dc-a731d2aa00aa}",
                        pageName:
                          "Requirements for domestic systematically important banks",
                        displayName:
                          "Requirements for domestic systematically important banks",
                        altDisplayName: "",
                        path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/capital-adequacy-framework/requirements-for-domestic-systematically-important-banks",
                        isExternalLink: false,
                        children: [],
                      },
                      {
                        id: "{e7480e76-abdb-4b3d-ba5d-5dd89bafad49}",
                        pageName: "Restructure of banking supervision handbook",
                        displayName:
                          "Restructure of banking supervision handbook",
                        altDisplayName: "",
                        path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/capital-adequacy-framework/restructure-of-banking-supervision-handbook",
                        isExternalLink: false,
                        children: [],
                      },
                    ],
                  },
                  {
                    id: "{b71beb16-6b24-4569-b86a-1a46e6bfe8f2}",
                    pageName: "Banking supervision handbook",
                    displayName: "Banking supervision handbook",
                    altDisplayName: "",
                    path: "",
                    isExternalLink: false,
                    children: [],
                  },
                  {
                    id: "{9a0c4a65-70a9-410a-a054-31db7ebf7bea}",
                    pageName: "Banks corporate governance",
                    displayName: "Banks corporate governance",
                    altDisplayName: "",
                    path: "",
                    isExternalLink: false,
                    children: [],
                  },
                  {
                    id: "{9d30bb45-0364-4bce-be15-34255930a404}",
                    pageName: "Connected exposures policy",
                    displayName: "Connected exposures policy",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/connected-exposures-policy",
                    isExternalLink: false,
                    children: [],
                  },
                  {
                    id: "{a0128604-b327-4c8a-bfb9-e7540fb92c1f}",
                    pageName: "Credit rating of banks in NZ",
                    displayName: "Credit rating of banks in NZ",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/credit-rating-of-banks-in-nz",
                    isExternalLink: false,
                    children: [],
                  },
                  {
                    id: "{a214ed8c-b1a8-4893-a3e3-6fbbae3b2e54}",
                    pageName: "Disclosure regime for banks",
                    displayName: "Disclosure regime for banks",
                    altDisplayName: "",
                    path: "",
                    isExternalLink: false,
                    children: [],
                  },
                  {
                    id: "{43f0168c-b588-4c48-b549-6707523f2991}",
                    pageName: "Liquidity policy for banks",
                    displayName: "Liquidity policy for banks",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/liquidity-policy-for-banks",
                    isExternalLink: false,
                    children: [],
                  },
                  {
                    id: "{b07f07ce-f7b6-48a4-99f9-8649f4baa56b}",
                    pageName: "Open bank resolution",
                    displayName: "Open bank resolution",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/banking-oversight/standards-and-requirements/open-bank-resolution",
                    isExternalLink: false,
                    children: [],
                  },
                  {
                    id: "{4ce85f67-dcb9-4b06-ba02-0707bb688abd}",
                    pageName: "Outsourcing policy for banks",
                    displayName: "Outsourcing policy for banks",
                    altDisplayName: "",
                    path: "",
                    isExternalLink: false,
                    children: [],
                  },
                ],
              },
              {
                id: "{0c376036-93ae-4666-957b-7c603dc60bc4}",
                pageName: "Resources for Banks",
                displayName: "Resource for Banks",
                altDisplayName: "",
                path: "/what-we-do/regulation-and-supervision/banking-oversight/resources-for-banks",
                isExternalLink: false,
                children: [
                  {
                    id: "{d992c259-b87b-48c7-a861-229badf9d95d}",
                    pageName: "Applying for bank registration",
                    displayName: "Applying for bank registration",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/banking-oversight/resources-for-banks/applying-for-bank-registration",
                    isExternalLink: false,
                    children: [],
                  },
                  {
                    id: "{a791f9f7-86fe-4eda-be85-7e3ee25b8fc7}",
                    pageName: "How we develop regulation",
                    displayName: "How we develop regulation",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/banking-oversight/resources-for-banks/how-we-develop-regulation",
                    isExternalLink: false,
                    children: [],
                  },
                  {
                    id: "{12043972-e2c3-4f28-86de-7b94f844e5ef}",
                    pageName: "Licensing and guidance for banks",
                    displayName: "Licensing and guidance for banks",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/banking-oversight/resources-for-banks/licensing-and-guidance-for-banks",
                    isExternalLink: false,
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: "{3d030609-c130-43ce-83eb-3ccb5a8e816a}",
            pageName: "Cross-sector oversight",
            displayName: "Cross-sector oversight",
            altDisplayName: "",
            path: "/what-we-do/regulation-and-supervision/cross-sector-oversight",
            isExternalLink: false,
            children: [
              {
                id: "{aef27757-3cc7-4d75-994e-a61fb215be37}",
                pageName: "Approach to policy-making",
                displayName: "Approach to policy-making",
                altDisplayName: "",
                path: "/what-we-do/regulation-and-supervision/cross-sector-oversight/approach-to-policy-making",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{d276fb3d-0a09-4fbe-9ad1-77354184e583}",
                pageName: "Approach to supervision",
                displayName: "Approach to supervision",
                altDisplayName: "",
                path: "/what-we-do/regulation-and-supervision/cross-sector-oversight/approach-to-supervision",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{ca2d3e62-e89e-4a62-ba0d-49295a66f796}",
                pageName: "Financial Sector Assessment",
                displayName: "Financial Sector Assessment",
                altDisplayName: "",
                path: "/what-we-do/regulation-and-supervision/cross-sector-oversight/financial-sector-assessment",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{a4dcc347-5716-433d-bb37-8722921636f1}",
                pageName: "Improving Cyber resilience for regulated entities",
                displayName:
                  "Improving Cyber resilience for regulated entities",
                altDisplayName: "",
                path: "/what-we-do/regulation-and-supervision/cross-sector-oversight/improving-cyber-resilience-for-regulated-entities",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{eb8060d0-ca04-4869-a1b6-2256b56cccd9}",
                pageName: "Crisis Management",
                displayName: "Crisis Management",
                altDisplayName: "",
                path: "/what-we-do/regulation-and-supervision/cross-sector-oversight/crisis-management",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{1752d050-10ec-4e7f-83ad-480b3a641b3e}",
                pageName: "Anti-money laundering",
                displayName: "Anti-money laundering",
                altDisplayName: "",
                path: "",
                isExternalLink: false,
                children: [
                  {
                    id: "{2768e4db-6589-4e28-8105-8d4a597b5cd4}",
                    pageName:
                      "Anti-money laundering and countering terrorism financing",
                    displayName:
                      "Anti-money laundering and countering terrorism financing",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/cross-sector-oversight/anti-money-laundering/anti-money-laundering-and-countering-terrorism-financing",
                    isExternalLink: false,
                    children: [],
                  },
                  {
                    id: "{180c9d1c-7970-4075-8c47-30fb791ca64a}",
                    pageName:
                      "Anti-money laundering and financing terrorism legislation",
                    displayName:
                      "Anti-money laundering and countering terrorism legislation",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/cross-sector-oversight/anti-money-laundering/anti-money-laundering-and-financing-terrorism-legislation",
                    isExternalLink: false,
                    children: [],
                  },
                  {
                    id: "{c9361138-c786-487d-9aac-0add85545776}",
                    pageName: "Anti-money laundering guidance and resources",
                    displayName: "Anti-money laundering guidance and resources",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/cross-sector-oversight/anti-money-laundering/anti-money-laundering-guidance-and-resources",
                    isExternalLink: false,
                    children: [],
                  },
                  {
                    id: "{0cd52449-122b-43d9-8ab7-d8f9aaf4d7bf}",
                    pageName:
                      "Complying with the anti-money laundering legislation",
                    displayName:
                      "Complying with anti-money laundering legislation",
                    altDisplayName: "",
                    path: "/what-we-do/regulation-and-supervision/cross-sector-oversight/anti-money-laundering/complying-with-the-anti-money-laundering-legislation",
                    isExternalLink: false,
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: "{abb2649f-637e-48eb-a00b-35dbe1cec7e1}",
            pageName: "Financial market infrastructures oversight",
            displayName: "Financial market infrastructures oversight",
            altDisplayName: "",
            path: "",
            isExternalLink: false,
            children: [
              {
                id: "{29d43934-ae10-4e75-9954-275850ee751d}",
                pageName: "Developing the legislative framework",
                displayName: "Developing the legislative framework",
                altDisplayName: "",
                path: "",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{0ed8896a-4acf-499b-bc17-7fea34788429}",
                pageName: "Link to Payment and Settlement services",
                displayName: "Link to Payment and Settlement services",
                altDisplayName: "",
                path: "",
                isExternalLink: false,
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "{3b0e594c-f80c-422d-86ad-36fd376817b1}",
        pageName: "Money and cash",
        displayName: "Money \u0026 cash",
        altDisplayName: "",
        path: "/what-we-do/money-and-cash",
        isExternalLink: false,
        children: [
          {
            id: "{26e09034-5066-48be-aac6-18d35f788753}",
            pageName: "Banknotes and coins",
            displayName: "Banknotes and coins",
            altDisplayName: "",
            path: "/what-we-do/money-and-cash/banknotes-and-coins",
            isExternalLink: true,
            children: [
              {
                id: "{23738715-c77e-4b9c-ac04-659c2f3e1ae6}",
                pageName: "Banknotes",
                displayName: "Banknotes in circulation",
                altDisplayName: "",
                path: "/what-we-do/money-and-cash/banknotes-and-coins/banknotes",
                isExternalLink: false,
                children: [],
              },
              {
                id: "{db380103-6692-4336-9412-7b8f207427ef}",
                pageName: "Coins",
                displayName: "Coins",
                altDisplayName: "",
                path: "/what-we-do/money-and-cash/banknotes-and-coins/coins",
                isExternalLink: true,
                children: [],
              },
              {
                id: "{d9899760-5ad5-46b3-9187-c2f21161a7ab}",
                pageName: "Level 4",
                displayName: "Level 4",
                altDisplayName: "Te Reo Title Level 4",
                path: "",
                isExternalLink: false,
                children: [
                  {
                    id: "{7678e2eb-a044-460c-9225-c553b8315a97}",
                    pageName: "Level 5",
                    displayName: "Level 5",
                    altDisplayName: "Te Reo Title Level 5",
                    path: "",
                    isExternalLink: false,
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: "{97e35e47-84a0-44dc-ada0-a0bb37c9ee37}",
            pageName: "How you may use images of currency",
            displayName: "How you may use images of currency",
            altDisplayName: "",
            path: "/what-we-do/money-and-cash/how-you-may-use-images-of-currency",
            isExternalLink: false,
            children: [
              {
                id: "{e6e3f979-69bf-455d-a57b-c0467b0cbfdd}",
                pageName: "Level 3 v1",
                displayName: "Level 3",
                altDisplayName: "Te Reo Title Level 3",
                path: "",
                isExternalLink: false,
                children: [
                  {
                    id: "{5eeeeba0-1a38-4f83-9eeb-a32eea8a0e06}",
                    pageName: "Level 4 v1",
                    displayName: "Level 4",
                    altDisplayName: "Te Reo Title Level 4",
                    path: "",
                    isExternalLink: false,
                    children: [
                      {
                        id: "{260a581e-a045-49b8-9927-1bd454d5290a}",
                        pageName: "Level 5 v1",
                        displayName: "Level 5",
                        altDisplayName: "Te Reo Title Level 5",
                        path: "",
                        isExternalLink: false,
                        children: [],
                      },
                    ],
                  },
                ],
              },
              {
                id: "{83afdfc7-9daf-4610-bad9-3d7a0edaa04f}",
                pageName: "Level 3 v2",
                displayName: "Level 3",
                altDisplayName: "Te Reo Title Level 3",
                path: "",
                isExternalLink: false,
                children: [
                  {
                    id: "{6cd08987-c433-430a-b8c7-d1cc2b69f490}",
                    pageName: "Level 4 v2",
                    displayName: "Level 4",
                    altDisplayName: "Te Reo Title Level 4",
                    path: "",
                    isExternalLink: false,
                    children: [
                      {
                        id: "{19eccbbf-100a-408b-a554-1db5c5c5575e}",
                        pageName: "Level 5 v2",
                        displayName: "Level 5",
                        altDisplayName: "Te Reo Title Level 5",
                        path: "",
                        isExternalLink: false,
                        children: [],
                      },
                    ],
                  },
                ],
              },
              {
                id: "{0aa8d0d2-1013-4f87-93ff-e3a11324a85a}",
                pageName: "Level 3 v3",
                displayName: "Level 3",
                altDisplayName: "Te Reo Title Level 3",
                path: "",
                isExternalLink: false,
                children: [
                  {
                    id: "{e5ba61e3-7dc7-4268-bb77-b5e5d366c911}",
                    pageName: "Level 4 v3",
                    displayName: "Level 4",
                    altDisplayName: "Te Reo Title Level 4",
                    path: "",
                    isExternalLink: false,
                    children: [
                      {
                        id: "{9ed5dccb-20a1-4c70-9143-d7a344beb21d}",
                        pageName: "Level 5 v3",
                        displayName: "Level 5",
                        altDisplayName: "Te Reo Title Level 5",
                        path: "",
                        isExternalLink: false,
                        children: [],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            id: "{f6c166d3-c309-4e5b-939a-d63de945fbbb}",
            pageName: "The future of money",
            displayName: "The future of money",
            altDisplayName: "",
            path: "/what-we-do/money-and-cash/the-future-of-money",
            isExternalLink: true,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "{b3eaa1df-a93f-4c27-b69d-4cea61655700}",
    pageName: "Knowledge base",
    displayName: "Knowledge base",
    altDisplayName: "Te reo translation",
    path: "/knowledge-base",
    isExternalLink: false,
    children: [
      {
        id: "{1e984646-c431-46d8-b4fc-7cae5b8e5cbd}",
        pageName: "Explainers",
        displayName: "Explainers",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
      {
        id: "{a8c02238-3c50-44b3-a268-74dd67df09c4}",
        pageName: "Fact sheets and guides",
        displayName: "Fact sheets \u0026 guides",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
      {
        id: "{8c7b5928-9dfc-4098-9c8a-9eb11c0b6390}",
        pageName: "Resources for schools",
        displayName: "Resources for schools",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
    ],
  },
  {
    id: "{ca9e3bdb-ee6f-4732-8db6-adb3b6ef1e04}",
    pageName: "News and publications",
    displayName: "News \u0026 publications",
    altDisplayName: "Te reo translation",
    path: "",
    isExternalLink: false,
    children: [
      {
        id: "{77ce13f2-afec-46df-ac00-b7a73f008a4c}",
        pageName: "News",
        displayName: "Newsroom",
        altDisplayName: "",
        path: "/news",
        isExternalLink: false,
        children: [],
      },
      {
        id: "{37692817-861b-4d74-9533-ded2d788e0b1}",
        pageName: "Publications",
        displayName: "Publications",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
      {
        id: "{25a35837-8ac5-47a9-8bb5-3321b015d043}",
        pageName: "Events",
        displayName: "Events",
        altDisplayName: "",
        path: "/events",
        isExternalLink: false,
        children: [],
      },
      {
        id: "{8062b633-4492-4eae-9de2-704289fce080}",
        pageName: "Speeches",
        displayName: "Speeches",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
    ],
  },
  {
    id: "{8d1e7d55-39a5-4a10-b379-cf3963844a32}",
    pageName: "Research",
    displayName: "Research",
    altDisplayName: "Te reo translation",
    path: "",
    isExternalLink: false,
    children: [
      {
        id: "{6d07aa76-4e85-4d2d-bdf2-cdeaabcbbda3}",
        pageName: "Our research and analysis",
        displayName: "Our research and analysis",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
      {
        id: "{b9631b80-a4c1-4f67-abfa-ce32a6a2e824}",
        pageName: "Opportunities for researchers",
        displayName: "Opportunities for researchers",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
    ],
  },
  {
    id: "{ce533a04-7d3c-449f-b79f-b94c7eb87b3d}",
    pageName: "Statistics",
    displayName: "Statistics",
    altDisplayName: "Te reo translation",
    path: "",
    isExternalLink: true,
    children: [],
  },
  {
    id: "{0ed551a1-a529-4b1e-981b-a02e754f4ffc}",
    pageName: "About us",
    displayName: "About us",
    altDisplayName: "Te reo translation",
    path: "",
    isExternalLink: false,
    children: [
      {
        id: "{72906b4d-a4a5-421f-b9fb-ebe1cfddd88d}",
        pageName: "Who we are",
        displayName: "Who we are",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
      {
        id: "{1d716bf7-d1c4-4218-809a-3f755d7817fd}",
        pageName: "What we do",
        displayName: "What we do",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
      {
        id: "{dc53a71e-1e62-4f04-9f88-8f8ec9fb5c8b}",
        pageName: "How we work",
        displayName: "How we work",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
      {
        id: "{09c1341b-0209-4563-b5bf-c14ecb2488b6}",
        pageName: "Responsibility and Accountability",
        displayName: "Responsibility \u0026 Accountability",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
      {
        id: "{fce69360-3d86-479f-9dde-fd55a51a2572}",
        pageName: "Our history",
        displayName: "Our history",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
    ],
  },
  {
    id: "{bf08d265-6a7d-41e5-96ae-1747859531dd}",
    pageName: "Careers",
    displayName: "Careers",
    altDisplayName: "Te reo translation",
    path: "",
    isExternalLink: false,
    children: [
      {
        id: "{ccdff3c5-754a-49bb-8f51-e2aea87b9369}",
        pageName: "Early careers",
        displayName: "Early careers",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
      {
        id: "{f3b36499-eb5e-4b9e-a949-32d547d33f9a}",
        pageName: "Why RBNZ",
        displayName: "Why RBNZ",
        altDisplayName: "",
        path: "",
        isExternalLink: false,
        children: [],
      },
    ],
  },
  {
    id: "{bf08d265-6a7d-41e5-96ae-1747859531ff}",
    pageName: "",
    displayName: "",
    altDisplayName: "Glossary",
    path: "",
    isExternalLink: false,
    children: [],
  },
];
